// La mina: constantes, materiales, peligros, zonas y piezas. Ver docs/06-mina.md.
// Todo el equilibrio vive aquí; el motor no conoce ningún nombre.

import type { HazardDef, MaterialDef, MineDef, PieceDef, ZoneDef } from './types.ts';

export const MINE: MineDef = {
  zoneLength: 20,
  hpBase: 8,
  hpGrowth: 1.16,
  coinBase: 2,
  coinGrowth: 1.12,
  baseDps: 1,
  tapSeconds: 1,
  startCoins: 20,
  hazardFloor: 0.25,
  milestones: [10, 25, 50, 100],
  milestoneMult: 2,
  plumaCoef: 0.05,
  plumaExp: 1.6,
  perPluma: 0.02,
  offlineHours: 2,
};

export const MATERIALS: MaterialDef[] = [
  { id: 'raices', name: 'Raíces', emoji: '🌿' },
  { id: 'arcilla', name: 'Arcilla', emoji: '🧱' },
  { id: 'piedra', name: 'Piedra', emoji: '🪨' },
  { id: 'cobre', name: 'Cobre', emoji: '🟠' },
  { id: 'hielo', name: 'Hielo', emoji: '🧊' },
  { id: 'cristal', name: 'Cristal', emoji: '💎' },
  { id: 'obsidiana', name: 'Obsidiana', emoji: '⬛' },
  { id: 'estrella', name: 'Polvo de estrella', emoji: '✨' },
];

export const HAZARDS: HazardDef[] = [
  { id: 'humedad', name: 'Humedad', emoji: '💧' },
  { id: 'derrumbes', name: 'Derrumbes', emoji: '🪨' },
  { id: 'oscuridad', name: 'Oscuridad', emoji: '🌑' },
  { id: 'frio', name: 'Frío', emoji: '🥶' },
  { id: 'resplandor', name: 'Resplandor', emoji: '😎' },
  { id: 'calor', name: 'Calor', emoji: '🔥' },
  { id: 'gas', name: 'Gas', emoji: '☁️' },
];

export const ZONES: ZoneDef[] = [
  { id: 'tierra', name: 'Tierra blanda', emoji: '🟫', flavor: 'Fácil de cavar y huele a hogar.', material: 'raices', hazard: null },
  { id: 'arcilla', name: 'Arcilla', emoji: '🧱', flavor: 'Pegajosa: sin botas, cada paso cuesta el doble.', material: 'arcilla', hazard: 'humedad' },
  { id: 'roca', name: 'Roca', emoji: '🪨', flavor: 'Dura, y de vez en cuando se cae un trozo.', material: 'piedra', hazard: 'derrumbes' },
  { id: 'cueva', name: 'Cueva oscura', emoji: '🕳️', flavor: 'Aquí no se ve nada sin una buena luz.', material: 'cobre', hazard: 'oscuridad' },
  { id: 'hielo', name: 'Cueva de hielo', emoji: '🧊', flavor: 'Hace tanto frío que hasta los ronquidos se congelan.', material: 'hielo', hazard: 'frio' },
  { id: 'cristales', name: 'Cristales', emoji: '💎', flavor: 'Brilla tanto que cuesta mirar el suelo.', material: 'cristal', hazard: 'resplandor' },
  { id: 'magma', name: 'Magma', emoji: '🌋', flavor: 'La roca está blanda porque está derretida.', material: 'obsidiana', hazard: 'calor' },
  { id: 'abismo', name: 'El abismo', emoji: '🌌', flavor: 'Sin fondo, sin aire y con un silencio raro.', material: 'estrella', hazard: 'gas' },
];

/** Cada pieza de resistencia pide un nivel `needBase + needStep · zona` para anular su peligro. */
const resist = (hazard: string) => ({ kind: 'resist' as const, hazard, needBase: 5, needStep: 3 });

export const PIECES: PieceDef[] = [
  {
    id: 'rascador',
    name: 'Rascador de hocico',
    emoji: '⛏️',
    flavor: 'Rasca la tierra con más ganas que nadie.',
    effect: { kind: 'dig', perLevel: 1 },
    baseCost: 10,
    costGrowth: 1.15,
    material: null,
    materialBase: 0,
    maxLevel: 100,
    unlock: { depth: 1, ascensions: 0 },
  },
  {
    id: 'botas',
    name: 'Botas de goma',
    emoji: '🥾',
    flavor: 'Para no quedarse pegado en el barro.',
    effect: resist('humedad'),
    baseCost: 60,
    costGrowth: 1.2,
    material: 'raices',
    materialBase: 4,
    maxLevel: 100,
    unlock: { depth: 5, ascensions: 0 },
  },
  {
    id: 'guantes',
    name: 'Guantes de lana',
    emoji: '🧤',
    flavor: 'Cada toque cuenta más con las manos calentitas.',
    effect: { kind: 'tap', perLevel: 0.25 },
    baseCost: 40,
    costGrowth: 1.17,
    material: null,
    materialBase: 0,
    maxLevel: 100,
    unlock: { depth: 3, ascensions: 0 },
  },
  {
    id: 'corona',
    name: 'Corona de latón',
    emoji: '👑',
    flavor: 'Los bloques sueltan más monedas ante la realeza.',
    effect: { kind: 'coinMult', perLevel: 0.1 },
    baseCost: 120,
    costGrowth: 1.2,
    material: 'raices',
    materialBase: 6,
    maxLevel: 100,
    unlock: { depth: 8, ascensions: 0 },
  },
  {
    id: 'casco',
    name: 'Casco minero',
    emoji: '⛑️',
    flavor: 'Los trozos de roca rebotan sin hacer daño.',
    effect: resist('derrumbes'),
    baseCost: 500,
    costGrowth: 1.22,
    material: 'arcilla',
    materialBase: 5,
    maxLevel: 100,
    unlock: { depth: 18, ascensions: 0 },
  },
  {
    id: 'mochila',
    name: 'Mochila con remiendos',
    emoji: '🎒',
    flavor: 'Caben más materiales en cada viaje.',
    effect: { kind: 'materialMult', perLevel: 0.15 },
    baseCost: 800,
    costGrowth: 1.2,
    material: 'arcilla',
    materialBase: 8,
    maxLevel: 100,
    unlock: { depth: 15, ascensions: 1 },
  },
  {
    id: 'linterna',
    name: 'Linterna de luciérnagas',
    emoji: '🏮',
    flavor: 'Ilumina sin asustar a nadie.',
    effect: resist('oscuridad'),
    baseCost: 3000,
    costGrowth: 1.23,
    material: 'piedra',
    materialBase: 6,
    maxLevel: 100,
    unlock: { depth: 38, ascensions: 1 },
  },
  {
    id: 'dinamita',
    name: 'Dinamita de feria',
    emoji: '🧨',
    flavor: 'Un botón, un estruendo y media mina avanzada.',
    effect: { kind: 'burst', baseSeconds: 30, perLevel: 6, cooldown: 90 },
    baseCost: 5000,
    costGrowth: 1.22,
    material: 'piedra',
    materialBase: 8,
    maxLevel: 100,
    unlock: { depth: 30, ascensions: 2 },
  },
  {
    id: 'capa',
    name: 'Capa para el frío',
    emoji: '🧣',
    flavor: 'Calentita, esponjosa y con capucha.',
    effect: resist('frio'),
    baseCost: 15000,
    costGrowth: 1.24,
    material: 'cobre',
    materialBase: 7,
    maxLevel: 100,
    unlock: { depth: 58, ascensions: 2 },
  },
  {
    id: 'topo',
    name: 'Topo ayudante',
    emoji: '🦔',
    flavor: 'Cava a su aire y no pide nada a cambio. Casi nada.',
    effect: { kind: 'helper', perLevel: 6 },
    baseCost: 30000,
    costGrowth: 1.22,
    material: 'cobre',
    materialBase: 9,
    maxLevel: 100,
    unlock: { depth: 50, ascensions: 3 },
  },
  {
    id: 'gafas',
    name: 'Gafas de sol',
    emoji: '🕶️',
    flavor: 'Para ir a lo suyo sin entornar los ojos.',
    effect: resist('resplandor'),
    baseCost: 100000,
    costGrowth: 1.25,
    material: 'hielo',
    materialBase: 8,
    maxLevel: 100,
    unlock: { depth: 78, ascensions: 3 },
  },
  {
    id: 'taladro',
    name: 'Taladro de vapor',
    emoji: '🛠️',
    flavor: 'Hace ruido, humo y mucho progreso.',
    effect: { kind: 'digMult', perLevel: 0.2 },
    baseCost: 200000,
    costGrowth: 1.24,
    material: 'hielo',
    materialBase: 10,
    maxLevel: 100,
    unlock: { depth: 70, ascensions: 4 },
  },
  {
    id: 'traje',
    name: 'Traje ignífugo',
    emoji: '🧯',
    flavor: 'La lava es solo una charca muy caliente.',
    effect: resist('calor'),
    baseCost: 600000,
    costGrowth: 1.26,
    material: 'cristal',
    materialBase: 9,
    maxLevel: 100,
    unlock: { depth: 98, ascensions: 5 },
  },
  {
    id: 'mascara',
    name: 'Máscara de aire',
    emoji: '😷',
    flavor: 'Respirar es lo primero, incluso a esta profundidad.',
    effect: resist('gas'),
    baseCost: 2000000,
    costGrowth: 1.27,
    material: 'obsidiana',
    materialBase: 10,
    maxLevel: 100,
    unlock: { depth: 118, ascensions: 6 },
  },
];
